package xconn

const (
	JsonWebsocketProtocol    = "wamp.2.json"
	MsgpackWebsocketProtocol = "wamp.2.msgpack"
	CborWebsocketProtocol    = "wamp.2.cbor"
	ProtobufSubProtocol      = "wamp.2.protobuf"

	CloseGoodByeAndOut  = "wamp.close.goodbye_and_out"
	CloseCloseRealm     = "wamp.close.close_realm"
	CloseSystemShutdown = "wamp.close.system_shutdown"
	CloseKilled         = "wamp.close.killed"

	ErrNoMatchingAuthMethod       = "wamp.error.no_matching_auth_method"
	ErrNoSuchRealm                = "wamp.error.no_such_realm"
	ErrNoSuchRole                 = "wamp.error.no_such_role"
	ErrNoSuchPrincipal            = "wamp.error.no_such_principal"
	ErrNoSuchSession              = "wamp.error.no_such_session"
	ErrAuthenticationDenied       = "wamp.error.authentication_denied"
	ErrAuthenticationFailed       = "wamp.error.authentication_failed"
	ErrAuthenticationRequired     = "wamp.error.authentication_required"
	ErrAuthorizationDenied        = "wamp.error.authorization_denied"
	ErrAuthorizationFailed        = "wamp.error.authorization_failed"
	ErrAuthorizationRequired      = "wamp.error.authorization_required"
	ErrTimeout                    = "wamp.error.timeout"
	ErrOptionNotAllowed           = "wamp.error.option_not_allowed"
	ErrOptionDisallowedDiscloseMe = "wamp.error.option_disallowed.disclose_me"
	ErrNetworkFailure             = "wamp.error.network_failure"
	ErrUnavailable                = "wamp.error.unavailable"
	ErrNoAvailableCallee          = "wamp.error.no_available_callee"
	ErrFeatureNotSupported        = "wamp.error.feature_not_supported"
	ErrInvalidURI                 = "wamp.error.invalid_uri"
	ErrNoSuchProcedure            = "wamp.error.no_such_procedure"
	ErrProcedureAlreadyExists     = "wamp.error.procedure_already_exists"
	ErrNoSuchRegistration         = "wamp.error.no_such_registration"
	ErrNoSuchSubscription         = "wamp.error.no_such_subscription"
	ErrInvalidArgument            = "wamp.error.invalid_argument"
	ErrCanceled                   = "wamp.error.canceled"
	ErrPayloadSizeExceeded        = "wamp.error.payload_size_exceeded"
	ErrProtocolViolation          = "wamp.error.protocol_violation"
	ErrNotAuthorized              = "wamp.error.not_authorized"
)
